id = "1"
name = "bank name"
difficulty = "easy"
topic = "general"
hidden = true

[[questions]]
question = "this is a question?"
answer = [ "yes", "true" ]

[[questions]]
question = "no."
answer = [ "no", "false" ]
